packages:
  - 'packages/*'

# pnpm-workspace.yaml文件是pnpm工作区配置文件，
# 用于定义工作区中的包和依赖关系。在这个文件中，我们定义了一个工作区，
# 其中包含了一个名为"packages"的目录，该目录下的所有子目录都被认为是工作区中的包。这样，我们就可以在工作区中统一管理所有的包和依赖关系，方便进行版本控制和依赖管理。
# 在这个文件中，我们还可以定义工作区中的公共依赖关系，例如：
# 
#   dependencies:
#     react: ^17.0.0
#     react-dom: ^17.0.0
# 
# 这将使得工作区中的所有包都默认依赖react和react-dom，并且版本号都是^17.0.0。这样，我们就可以在所有包中使用相同的依赖版本，避免版本冲突。
# 
# 此外，我们还可以定义工作区中的私有依赖关系，例如：
# 
#   privateDependencies: